### ISSUE TITLE
why not work Key Logger

### ISSUE THREAD

**Issue by Toxenskiy** [SaherBlueEagle/XPR-2020-Free#5]
why not work Key Logger
![mdmsd](https://user-images.githubusercontent.com/55586522/97108776-b5972900-16e0-11eb-9aa1-e84dfb303798.png)

**Comment by SaherBlueEagle** [comment]
i think that is a simple Bug , not critical , you can use external keylogger and download the log file from victim , as the program is free this issue not critical Bug 
Thank you for understanding

**Comment by SaherBlueEagle** [comment]
i think that is a simple Bug , not critical , you can use external keylogger and download the log file from victim , as the program is free this issue not critical Bug
Thank you for understanding
